layout_spectrum: 0.4802867
color:
  saturation: 0.8905171
  brandStrength: 0.7885305
  lightness: 0.7352023
  brandColors:
    - '#000000'
    - '#01FFFF'
    - '#B5FFFF'
    - '#7F8080'
    - '#AE0000'
  rhythmicContrast: 0.2222222
typography_spectrum: 0.09498208
name: Autoberatung
