layout_spectrum: 0.9354839
color:
  saturation: 1
  brandStrength: 0.7885305
  lightness: 1
  brandColors:
    - '#220521'
    - '#AFB6AF'
    - '#716374'
    - '#DBE8E1'
    - '#F2B92C'
  rhythmicContrast: 1
typography_spectrum: 0.09498208
name: Autoberatung
