layout_spectrum: 0.9354839
typography_spectrum: 0.9408602
color:
  saturation: 1
  brandStrength: 0.297491
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#1F2C3C'
    - '#AD7545'
    - '#D6A37B'
  rhythmicContrast: 1
name: Autoberatung
