layout_spectrum: 0.4605735
color:
  saturation: 0.2795699
  brandStrength: 0.297491
  lightness: 0.7759857
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#1F2C3C'
    - '#AD7545'
    - '#D6A37B'
  rhythmicContrast: 0.5071685
typography_spectrum: 0.9408602
name: Autoberatung
